# Generated by Django 4.1.3 on 2022-12-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_home_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category body types car'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Home Page, car model', 'verbose_name_plural': 'Home Page, car model'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='body type'),
        ),
    ]
